apiVersion: v1
kind: Secret
metadata:
  name: workervotacaosecret
type: Opaque
data:
  ConnectionAppInsights: <CONNECTION STRING APP INSIGHTS BASE64>
  ConnectionAzureEventHubs: <CONNECTION STRING AZURE EVENT HUBS BASE64>
  ConnectionAzureStorage: <CONNECTION STRING AZURE STORAGE BASE64>
  ConnectionSqlServer: <CONNECTION STRING SQL SERVER/AZURE SQL BASE64>